api_platform:
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        pdf: [ 'application/pdf' ]
        jpeg: [ 'image/jpeg' ]
    mapping:
        paths: ['%kernel.project_dir%/src/Entity', '%kernel.project_dir%/src/Api/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: 'X-AUTHENTICATION'
                type: 'header'
    defaults:
        pagination_client_items_per_page: true
        pagination_items_per_page: 50

    version: '1.0'
    show_webby: false

    # to debug nodes directly
    # enable_re_doc: false
    # enable_swagger_ui: false

