api_platform:
    formats:
        json: [ 'application/json' ]
        jsonld: ['application/ld+json']
        pdf: [ 'application/pdf' ]
        jpeg: [ 'image/jpeg' ]
    mapping:
        paths: ['%kernel.project_dir%/src/Entity', '%kernel.project_dir%/src/Api/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: 'X-AUTHENTICATION'
                type: 'header'
    collection:
        pagination:
            items_per_page: 30
            client_items_per_page: true

    version: '0.5.1'
    show_webby: false

    # to debug nodes directly
    # enable_re_doc: false
    # enable_swagger_ui: false

