# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    #http_method_override: true

    session:
        cookie_samesite: 'strict'

    #esi: true
    #fragments: true
    php_errors:
        log: true

    router:
        default_uri: '%env(BASE_URI)%'
