security:
    access_decision_manager:
        strategy: unanimous

    encoders:
        App\Entity\ConstructionManager: bcrypt

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        construction_manager_provider:
            id: App\Security\ConstructionManagerProvider

    firewalls:
        # disables authentication for assets and the profiler
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # main firewall for logged in users
        main:
            pattern:   ^/
            anonymous: ~
            provider: construction_manager_provider
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: dashboard
                csrf_token_generator: security.csrf.token_manager
                # field names for the username and password fields
                username_parameter: login[email]
                password_parameter: login[password]
            logout:
              path: login_logout
              target: /
            anonymous:    true
            remember_me:
              secret: '%env(APP_SECRET)%'
              lifetime: 604800
              path: /
              always_remember_me: true

    access_control:
        - { path: ^/api/external, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/support, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/email, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/external, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }

