security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        construction_managers:
            entity:
                class: 'App\Entity\ConstructionManager'
                property: 'email'
        api_tokens:
            id: App\Security\TokenUserProvider

    role_hierarchy:
        ROLE_ADMIN: [ROLE_CONSTRUCTION_MANAGER, ROLE_ALLOWED_TO_SWITCH]
        ROLE_CONSTRUCTION_MANAGER: [ROLE_ASSOCIATED_CONSTRUCTION_MANAGER]
        ROLE_ASSOCIATED_CONSTRUCTION_MANAGER: [ROLE_USER, ROLE_API_USER]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api/
            provider: api_tokens
            custom_authenticators:
                - App\Security\TokenAuthenticator
        main:
            provider: construction_managers
            form_login:
                login_path: login
                check_path: /login_check
                enable_csrf: true
                username_parameter: 'login[email]'
                password_parameter: 'login[password]'
                csrf_parameter: 'login[_token]'
                csrf_token_id: 'login'
            logout:
                path: logout
                # where to redirect after logout
                target: login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path: /
                always_remember_me: true
                samesite: 'strict'
            switch_user: true

    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin, role: ROLE_ADMIN }

        - { path: ^/login, role: PUBLIC_ACCESS }
        - { path: ^/recover, role: PUBLIC_ACCESS }
        - { path: ^/register, role: PUBLIC_ACCESS }
        - { path: ^/email, role: PUBLIC_ACCESS }
        - { path: ^/help, role: PUBLIC_ACCESS }
        - { path: ^/set_locale, role: PUBLIC_ACCESS }
        - { path: ^/api/construction_managers, role: PUBLIC_ACCESS, methods: [POST] } # API registration
        - { path: ^/api/docs, role: PUBLIC_ACCESS }
        - { path: ^/api/status, role: PUBLIC_ACCESS }

        # legacy URLs; catched by legacy URL controller
        - { path: '^/api/external.+', role: PUBLIC_ACCESS }
        - { path: '^/external/share/c.+', role: PUBLIC_ACCESS }

        - { path: '^/download/.+', role: PUBLIC_ACCESS }
        - { path: '^/resolve/.+', role: PUBLIC_ACCESS }
        - { path: '^/filtered/.+', role: PUBLIC_ACCESS }

        - { path: '^/api/construction_sites/[a-fA-F\d]{8}-(?:[a-fA-F\d]{4}-){3}[a-fA-F\d]{12}/image/.+', role: PUBLIC_ACCESS, methods: [GET] }
        - { path: '^/api/maps/[a-fA-F\d]{8}-(?:[a-fA-F\d]{4}-){3}[a-fA-F\d]{12}/file/.+', role: PUBLIC_ACCESS, methods: [GET] }
        - { path: '^/api/issues/[a-fA-F\d]{8}-(?:[a-fA-F\d]{4}-){3}[a-fA-F\d]{12}/image/.+', role: PUBLIC_ACCESS, methods: [GET] }
        - { path: '^/api/issues/render.+', role: PUBLIC_ACCESS, methods: [GET] }
        - { path: '^/api/issues/[a-fA-F\d]{8}-(?:[a-fA-F\d]{4}-){3}[a-fA-F\d]{12}/map/render.+', role: PUBLIC_ACCESS, methods: [GET] }

        - { path: ^/api, role: ROLE_API_USER }
        - { path: ^/set_locale, role: ROLE_USER }
        - { path: ^/, role: ROLE_ASSOCIATED_CONSTRUCTION_MANAGER }

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
