security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        construction_managers:
            entity:
                # the class of the entity that represents users
                class: 'App\Entity\ConstructionManager'
                # the property to query by - e.g. username, email, etc
                property: 'email'

    encoders:
        App\Entity\ConstructionManager:
            algorithm: auto

    role_hierarchy:
        ROLE_ADMIN: [ROLE_CONSTRUCTION_MANAGER, ROLE_ALLOWED_TO_SWITCH]
        ROLE_CONSTRUCTION_MANAGER: ROLE_ASSIGNED_CONSTRUCTION_MANAGER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: construction_managers
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
                    - App\Security\TokenAuthenticator
                entry_point: App\Security\LoginFormAuthenticator
            logout:
                path: logout
                # where to redirect after logout
                target: login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path: /
                always_remember_me: true
            switch_user: true

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/recover, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/email, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_CONSTRUCTION_MANAGER }
