security:
    access_decision_manager:
        strategy: unanimous

    encoders:
        App\Entity\FrontendUser: bcrypt
        App\Entity\BackendUser: bcrypt

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_FRONTEND_USER: ROLE_USER
        ROLE_BACKEND_USER: ROLE_USER

    providers:
        frontend_user_provider:
            id: App\Security\FrontendUserProvider
        backend_user_provider:
            id: App\Security\BackendUserProvider

    firewalls:
        # disables authentication for assets and the profiler
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # main firewall for logged in users
        frontend:
            pattern:   ^/frontend
            anonymous: ~
            provider: frontend_user_provider
            form_login:
                login_path: frontend_login_index
                check_path: frontend_login_check
                default_target_path: frontend_dashboard_index
                csrf_token_generator: security.csrf.token_manager
                # field names for the username and password fields
                username_parameter: login[email]
                password_parameter: login[password]
            logout:
              path: frontend_login_logout
              target: /
            anonymous:    true
            logout_on_user_change: true
            remember_me:
              secret: '%env(APP_SECRET)%'
              lifetime: 604800
              path: /
              always_remember_me: true

        #backend firewall for admins
        backend:
            pattern:   ^/backend
            anonymous: ~
            provider: backend_user_provider
            form_login:
                login_path: backend_login_index
                check_path: backend_login_check
                default_target_path: backend_dashboard_index
                csrf_token_generator: security.csrf.token_manager
                username_parameter: login[email]
                password_parameter: login[password]
            logout:
              path: backend_login_logout
              target: /
            anonymous:    true
            logout_on_user_change: true

    access_control:
        #all pages are public, specify roles inside the controller
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }