twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['form/form_layout.html.twig', 'form/fields.html.twig']
    paths:
        # point this wherever your css files live
        '%kernel.project_dir%/public/build': build
        '%kernel.project_dir%/public/build/images': images

    globals:
        env_support_email: '%env(SUPPORT_EMAIL)%'
