image: php:7.2

# Select what we should cache
cache:
  paths:
  - vendor/
  - node_modules/

before_script:
- cp phpunit.xml.dist phpunit.xml

# - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys E1DD270288B4E6030699E45FA1715D88E1DF1F24
# - su -c "echo 'deb http://ppa.launchpad.net/git-core/ppa/ubuntu trusty main' > /etc/apt/sources.list.d/git.list"


# install git, yarn
- apt-get update -y
- apt-get install git, yarn -y

# install frontend & build stuff
- yarn install
- yarn encore dev

# install phpunit
- curl --location --output /usr/local/bin/phpunit https://phar.phpunit.de/phpunit.phar
- chmod +x /usr/local/bin/phpunit

# install xdebug
- pecl install xdebug-2.6.0RC2

# enable php extensions
- docker-php-ext-enable xdebug
- docker-php-ext-enable zip
- docker-php-ext-enable sqlite3

# install composer
- curl -sS https://getcomposer.org/installer | php

# execute composer
- php composer.phar config --global discard-changes true
- php composer.phar install --dev

# warmup cache to avoid excessive memory usage
- php bin/console cache:warmup

# init db & data
- php bin/console doctrine:migrations:migrate -q
- php bin/console doctrine:fixtures:load -q

# test
test:default:
  script:
  - phpunit --configuration phpunit.xml --coverage-text --debug
