build:
    nodes:
        analysis:
            environment:
                node: v14
            project_setup:
                override: true
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis

tools:
    external_code_coverage: true

checks:
    php:
        code_rating: true
        duplication: true

filter:
    paths: ["src/*"]
