<?php

namespace App\Repository;

use App\Entity\ConstructionManager;
use Doctrine\ORM\EntityRepository;

/**
 * BuildingRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class BuildingRepository extends EntityRepository
{
    /**
     * @param ConstructionManager $appUser
     * @return mixed
     */
    public function findByAppUser(ConstructionManager $appUser)
    {
        return $this->createQueryBuilder('b')
            ->innerJoin('b.appUsers', 'au')
            ->where('au.id = :app_user_id')
            ->setParameter('app_user_id', $appUser->getId())
            ->getQuery()->getResult();
    }
}
