app:
    resource: "../src/Controller/"
    type:     annotation

app_api:
    resource: "../src/Controller/Api/"
    type:     annotation
    prefix:   /api

app_api_external:
    resource: "../src/Controller/Api/External/"
    type:     annotation
    prefix:   /api/external

app_external:
    resource: "../src/Controller/External/"
    type:     annotation
    prefix:   /external

app_external_api_share:
    resource: "../src/Controller/External/Api/Share"
    type:     annotation
    prefix:   /external/api/share

app_external_image:
    resource: "../src/Controller/External/Image/"
    type:     annotation
    prefix:   /external/image

app_external_report:
    resource: "../src/Controller/External/Report/"
    type:     annotation
    prefix:   /external/report