app:
    resource: "../src/Controller/"
    type:     annotation

app_api:
    resource: "../src/Controller/Api/"
    type:     annotation
    prefix:   /api

app_api_external:
    resource: "../src/Controller/Api/External/"
    type:     annotation
    prefix:   /api/external

app_external:
    resource: "../src/Controller/External/"
    type:     annotation
    prefix:   /external

app_external_api:
    resource: "../src/Controller/External/Api/"
    type:     annotation
    prefix:   /external/api