# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $mailerFromEmail: '%env(MAILER_FROM_EMAIL)%'
            $supportEmail: '%env(SUPPORT_EMAIL)%'
            $authorizationMethod: '%env(AUTHORIZATION_METHOD)%'
            $defaultUri: '%env(DEFAULT_URI)%'
            $environment: '%kernel.environment%'
            $publicDir: '%kernel.project_dir%/public'
            $reportAssetDir: '%kernel.project_dir%/assets/report'
            $needCaptcha: '%env(NEED_CAPTCHA)%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/Api/Entity'

    App\Api\OpenApi\OpenApiFactory:
       decorates: 'api_platform.openapi.factory'
       arguments: [ '@App\Api\OpenApi\OpenApiFactory.inner' ]
       autoconfigure: false

    # higher priority are called first
    App\Api\Provider\IssueGroupProvider:
        tags: [ { name: 'api_platform.collection_data_provider', priority: 3 } ]
        arguments:
            $collectionExtensions: !tagged api_platform.doctrine.orm.query_extension.collection
    App\Api\Provider\IssueSummaryProvider:
        tags: [ { name: 'api_platform.collection_data_provider', priority: 3 } ]
        arguments:
            $collectionExtensions: !tagged api_platform.doctrine.orm.query_extension.collection
    App\Api\Provider\IssueTimeseriesProvider:
        tags: [ { name: 'api_platform.collection_data_provider', priority: 3 } ]
        arguments:
            $collectionExtensions: !tagged api_platform.doctrine.orm.query_extension.collection

    App\Api\CustomController\IssuesRender:
        tags: [ 'controller.service_arguments']
    App\Api\CustomController\IssuesReport:
        tags: [ 'controller.service_arguments']

    'App\Api\Serializer\ConstructionSiteSerializer':
        bind: { $decoratedNormalizer: '@api_platform.jsonld.normalizer.item' }
    'App\Api\Serializer\CraftsmanSerializer':
        bind: { $decoratedNormalizer: '@api_platform.jsonld.normalizer.item' }
    'App\Api\Serializer\FilterSerializer':
        bind: { $decoratedNormalizer: '@api_platform.jsonld.normalizer.item' }
    'App\Api\Serializer\IssueSerializer':
        bind: { $decoratedNormalizer: '@api_platform.jsonld.normalizer.item' }
    'App\Api\Serializer\MapSerializer':
        bind: { $decoratedNormalizer: '@api_platform.jsonld.normalizer.item' }
    'App\Api\Serializer\IssueEventSerializer':
        bind: { $decoratedNormalizer: '@api_platform.jsonld.normalizer.item' }
