image: php:7.2

# Select what we should cache
cache:
  paths:
  - vendor/
  - node_modules/

before_script:
- cp phpunit.xml.dist phpunit.xml

# install git, yarn, nodejs, libmagickwand-dev (for imagick extension)
- apt-get update -y
- curl -sL https://deb.nodesource.com/setup_10.x | bash -
- apt-get install -y gnupg git nodejs libmagickwand-dev
- npm install -g yarn

# install & build frontend
- yarn install
- yarn encore dev

# install phpunit
- curl --location --output /usr/local/bin/phpunit https://phar.phpunit.de/phpunit.phar
- chmod +x /usr/local/bin/phpunit

# install xdebuug requirements
- pecl install xdebug-2.6.0RC2
- docker-php-ext-enable xdebug

# install imagick
- pecl install imagick-3.4.3
- docker-php-ext-enable imagick

# install composer
- curl -sS https://getcomposer.org/installer | php

# execute composer
- php composer.phar config --global discard-changes true
- php composer.phar install --dev

# warmup cache to avoid excessive memory usage
- php bin/console cache:warmup

# init db & data
- php bin/console doctrine:migrations:migrate -q
- php bin/console doctrine:fixtures:load -q

# test
test:default:
  script:
  - phpunit --configuration phpunit.xml --coverage-text --debug
